import { theme } from "../../../../styles/theme";

export const loginStyles = {
  input: {
    backgroundColor: "white",
    width: "100%",
    height: 50,
    marginTop: 5,
    borderWidth: 2,
    borderColor: "#cfcfcf",
    borderRadius: 5,
    fontSize: 16,
    paddingLeft: 10,
    paddingRight: 10,
    color: "#4d4d4d",
  },
  loginBtn: {
    width: "100%",
    height: 50,
    backgroundColor: "#4873E1",
    marginTop: 40,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 5,
  },
  bottomNavigationView: {
    width: "100%",
    height: "95%",
    padding: 20,
    borderTopLeftRadius: 40,
    borderTopRightRadius: 40,
    backgroundColor: "#1C1D21",
    shadowColor: "white",
    shadowOpacity: 4,
    shadowRadius: 4,
    shadowOffset: 2,
  },
  bottomTopContainer: {
    width: "100%",
    alignItems: "center",
    justifyContent: "space-between",
    flexDirection: "row",
  },
  loginButton: {
    width: "100%",
    height: 50,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 20,
    marginTop: 20,
  },
  loginButtonText: {
    fontSize: 20,
    color: "#111214",
    fontFamily: "TTNormsPro-Bold",
  },
  questionContainer: {
    width: "100%",
    justifyContent: "center",
    flexDirection: "row",
    marginTop: 30,
  },
  questionText: {
    color: theme.colors.grey,
    fontSize: 16,
    fontFamily: "TTNormsPro-Medium",
  },
  registrationBtn: {
    marginLeft: 5,
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.primary,
    paddingBottom: 2,
  },
  registrationBtnText: {
    color: theme.colors.primary,
    fontSize: 16,
    fontFamily: "TTNormsPro-Medium",
  },
  isForgotContainer: {
    width: "100%",
    alignItems: "center",
    marginTop: 8,
  },
  isForgotBtn: {
    borderBottomWidth: 1,
    borderBottomColor: theme.colors.primary,
    paddingBottom: 2,
  },
  isForgotText: {
    color: theme.colors.primary,
    fontSize: 16,
    fontFamily: "TTNormsPro-Medium",
  },
  img: {
    width: 100,
    height: 80,
    marginTop: 15,
  },
};
